import { ProductType } from "../types/product";

export const PRODUCTS: ProductType[] = [
  {
    id: 1,
    name: "Sữa tươi Vinamilk 1L",
    image: "/images/p1.jpg",
    onHand: 120,
    description: "Sữa tươi tiệt trùng Vinamilk không đường 1L.",
    salePrice: 32000,
    originalPrice: 36000,
    tag: ["new"],
  },
  {
    id: 2,
    name: "Trà xanh Không Độ",
    image: "/images/p2.jpg",
    onHand: 85,
    description: "Nước giải khát trà xanh hương chanh.",
    salePrice: 9000,
    originalPrice: 10000,
    tag: ["hot"],
  },
  {
    id: 3,
    name: "Mì Hảo Hảo Tôm Chua Cay",
    image: "/images/p3.jpg",
    onHand: 300,
    description: "Mì ăn liền Hảo Hảo hương tôm chua cay.",
    salePrice: 3500,
    originalPrice: 4000,
  },
  {
    id: 4,
    name: "Gạo ST25 5kg",
    image: "/images/p4.jpg",
    onHand: 50,
    description: "Gạo thơm thượng hạng ST25.",
    salePrice: 135000,
    originalPrice: 150000,
  },
  {
    id: 5,
    name: "Dầu ăn Tường An 1L",
    image: "/images/p5.jpg",
    onHand: 75,
    description: "Dầu ăn truyền thống Tường An loại 1 lít.",
    salePrice: 42000,
    originalPrice: 48000,
    tag: ["sale"],
  },
  {
    id: 6,
    name: "Nước mắm Nam Ngư 500ml",
    image: "/images/p6.jpg",
    onHand: 62,
    description: "Nước mắm Nam Ngư độ đạm 12°.",
    salePrice: 21000,
    originalPrice: 25000,
  },
  {
    id: 7,
    name: "Bánh Oreo Original",
    image: "/images/p7.jpg",
    onHand: 90,
    description: "Bánh quy kẹp kem Oreo truyền thống.",
    salePrice: 11000,
    originalPrice: 13000,
    tag: ["hot"],
  },
  {
    id: 8,
    name: "Coca-Cola lon 330ml",
    image: "/images/p8.jpg",
    onHand: 150,
    description: "Nước ngọt Coca-Cola lon 330ml.",
    salePrice: 8500,
    originalPrice: 10000,
  },
  {
    id: 9,
    name: "Trứng gà CP hộp 10 quả",
    image: "/images/p9.jpg",
    onHand: 40,
    description: "Trứng gà sạch CP giàu dinh dưỡng.",
    salePrice: 33000,
    originalPrice: 38000,
  },
  {
    id: 10,
    name: "Khăn giấy Kleenex 180 tờ",
    image: "/images/p10.jpg",
    onHand: 70,
    description: "Khăn giấy cao cấp Kleenex.",
    salePrice: 26000,
    originalPrice: 30000,
  },

  // 11 → 50 (tên thực tế)
  {
    id: 11,
    name: "Bánh mì hoa cúc",
    image: "/images/p11.jpg",
    onHand: 25,
    description: "Bánh mì hoa cúc mềm thơm.",
    salePrice: 55000,
    originalPrice: 65000,
  },
  {
    id: 12,
    name: "Sữa chua TH True Yogurt",
    image: "/images/p12.jpg",
    onHand: 140,
    description: "Sữa chua lên men tự nhiên TH.",
    salePrice: 7000,
    originalPrice: 8000,
  },
  {
    id: 13,
    name: "Nước suối Lavie 500ml",
    image: "/images/p13.jpg",
    onHand: 200,
    description: "Nước khoáng thiên nhiên Lavie.",
    salePrice: 5000,
    originalPrice: 6000,
  },
  {
    id: 14,
    name: "Muối i-ốt 500g",
    image: "/images/p14.jpg",
    onHand: 80,
    description: "Muối tinh i-ốt loại 500g.",
    salePrice: 6000,
    originalPrice: 8000,
  },
  {
    id: 15,
    name: "Tương ớt Cholimex",
    image: "/images/p15.jpg",
    onHand: 95,
    description: "Tương ớt ăn liền Cholimex.",
    salePrice: 11000,
    originalPrice: 13000,
  },
  {
    id: 16,
    name: "Bột canh Hải Châu",
    image: "/images/p16.jpg",
    onHand: 120,
    description: "Bột canh hương vị truyền thống.",
    salePrice: 8000,
    originalPrice: 9000,
  },
  {
    id: 17,
    name: "Xúc xích Đức Việt",
    image: "/images/p17.jpg",
    onHand: 50,
    description: "Xúc xích tiệt trùng Đức Việt.",
    salePrice: 32000,
    originalPrice: 36000,
  },
  {
    id: 18,
    name: "Dầu gội Clear Men 650g",
    image: "/images/p18.jpg",
    onHand: 40,
    description: "Dầu gội sạch gàu dành cho nam.",
    salePrice: 125000,
    originalPrice: 145000,
  },
  {
    id: 19,
    name: "Bánh Pía Tân Huê Viên",
    image: "/images/p19.jpg",
    onHand: 30,
    description: "Bánh pía sầu riêng đặc sản Sóc Trăng.",
    salePrice: 60000,
    originalPrice: 70000,
  },
  {
    id: 20,
    name: "Khô bò miếng 100g",
    image: "/images/p20.jpg",
    onHand: 20,
    description: "Khô bò đặc sản Tây Nguyên.",
    salePrice: 45000,
    originalPrice: 55000,
  },
  {
    id: 21,
    name: "Sữa đặc Ông Thọ",
    image: "/images/p21.jpg",
    onHand: 75,
    description: "Sữa đặc trắng Ông Thọ.",
    salePrice: 25000,
    originalPrice: 30000,
  },
  {
    id: 22,
    name: "Hạt nêm Knorr 400g",
    image: "/images/p22.jpg",
    onHand: 80,
    description: "Hạt nêm thịt thăn, xương ống và tủy.",
    salePrice: 38000,
    originalPrice: 42000,
  },
  {
    id: 23,
    name: "Nước tương Maggi",
    image: "/images/p23.jpg",
    onHand: 90,
    description: "Nước tương đậm đà hương vị.",
    salePrice: 15000,
    originalPrice: 18000,
  },
  {
    id: 24,
    name: "Phô mai Con Bò Cười",
    image: "/images/p24.jpg",
    onHand: 50,
    description: "Phô mai tam giác Con Bò Cười.",
    salePrice: 26000,
    originalPrice: 30000,
  },
  {
    id: 25,
    name: "Sữa rửa mặt Cetaphil 500ml",
    image: "/images/p25.jpg",
    onHand: 35,
    description: "Sữa rửa mặt dịu nhẹ Cetaphil.",
    salePrice: 285000,
    originalPrice: 320000,
  },
  {
    id: 26,
    name: "Mặt nạ Senka",
    image: "/images/p26.jpg",
    onHand: 100,
    description: "Mặt nạ dưỡng da Senka.",
    salePrice: 12000,
    originalPrice: 15000,
  },
  {
    id: 27,
    name: "Giấy vệ sinh Bless You",
    image: "/images/p27.jpg",
    onHand: 110,
    description: "Giấy vệ sinh 3 lớp cao cấp.",
    salePrice: 42000,
    originalPrice: 50000,
  },
  {
    id: 28,
    name: "Cafe G7 3in1",
    image: "/images/p28.jpg",
    onHand: 130,
    description: "Cafe hòa tan G7 3in1.",
    salePrice: 48000,
    originalPrice: 55000,
  },
  {
    id: 29,
    name: "Thịt nguội CP 200g",
    image: "/images/p29.jpg",
    onHand: 25,
    description: "Thịt nguội heo CP đóng gói.",
    salePrice: 45000,
    originalPrice: 52000,
  },
  {
    id: 30,
    name: "Bia Heineken lon",
    image: "/images/p30.jpg",
    onHand: 150,
    description: "Bia Heineken lon 330ml.",
    salePrice: 18000,
    originalPrice: 20000,
  },
  {
    id: 31,
    name: "Bánh gạo One One",
    image: "/images/p31.jpg",
    onHand: 60,
    description: "Bánh gạo giòn One One.",
    salePrice: 17000,
    originalPrice: 20000,
  },
  {
    id: 32,
    name: "Hạt điều rang muối 200g",
    image: "/images/p32.jpg",
    onHand: 25,
    description: "Hạt điều Bình Phước loại 1.",
    salePrice: 60000,
    originalPrice: 70000,
  },
  {
    id: 33,
    name: "Mật ong hoa nhãn 500ml",
    image: "/images/p33.jpg",
    onHand: 30,
    description: "Mật ong nguyên chất.",
    salePrice: 85000,
    originalPrice: 100000,
  },
  {
    id: 34,
    name: "Chà bông heo 100g",
    image: "/images/p34.jpg",
    onHand: 40,
    description: "Ruốc heo sấy khô.",
    salePrice: 35000,
    originalPrice: 40000,
  },
  {
    id: 35,
    name: "Bánh quy Cosy",
    image: "/images/p35.jpg",
    onHand: 75,
    description: "Bánh quy bơ Cosy.",
    salePrice: 26000,
    originalPrice: 30000,
  },
  {
    id: 36,
    name: "Nước ép táo Twister",
    image: "/images/p36.jpg",
    onHand: 90,
    description: "Nước ép trái cây Twister.",
    salePrice: 12000,
    originalPrice: 15000,
  },
  {
    id: 37,
    name: "Xịt khử mùi Romano 150ml",
    image: "/images/p37.jpg",
    onHand: 42,
    description: "Xịt khử mùi dành cho nam.",
    salePrice: 78000,
    originalPrice: 90000,
  },
  {
    id: 38,
    name: "Nước rửa chén Sunlight",
    image: "/images/p38.jpg",
    onHand: 120,
    description: "Nước rửa chén Sunlight hương chanh.",
    salePrice: 21000,
    originalPrice: 25000,
  },
  {
    id: 39,
    name: "Bột giặt Omo 3kg",
    image: "/images/p39.jpg",
    onHand: 65,
    description: "Bột giặt Omo sạch vượt trội.",
    salePrice: 120000,
    originalPrice: 135000,
  },
  {
    id: 40,
    name: "Nước xả Downy 2.3L",
    image: "/images/p40.jpg",
    onHand: 50,
    description: "Nước xả vải Downy đậm đặc.",
    salePrice: 145000,
    originalPrice: 165000,
  },
  {
    id: 41,
    name: "Ốc quế kem Merino",
    image: "/images/p41.jpg",
    onHand: 80,
    description: "Kem ốc quế Merino.",
    salePrice: 9000,
    originalPrice: 12000,
  },
  {
    id: 42,
    name: "Xúc xích CP 5 cây",
    image: "/images/p42.jpg",
    onHand: 100,
    description: "Xúc xích tiệt trùng CP.",
    salePrice: 27000,
    originalPrice: 32000,
  },
  {
    id: 43,
    name: "Chân gà rút xương",
    image: "/images/p43.jpg",
    onHand: 35,
    description: "Chân gà ngâm sả ớt.",
    salePrice: 32000,
    originalPrice: 40000,
  },
  {
    id: 44,
    name: "Nem chua Thanh Hóa",
    image: "/images/p44.jpg",
    onHand: 25,
    description: "Nem chua đặc sản Thanh Hóa.",
    salePrice: 55000,
    originalPrice: 65000,
  },
  {
    id: 45,
    name: "Sầu riêng Ri6 1kg",
    image: "/images/p45.jpg",
    onHand: 30,
    description: "Sầu riêng Ri6 tươi ngon.",
    salePrice: 120000,
    originalPrice: 150000,
  },
  {
    id: 46,
    name: "Chuối già Nam Mỹ 1kg",
    image: "/images/p46.jpg",
    onHand: 45,
    description: "Chuối tươi già Nam Mỹ.",
    salePrice: 28000,
    originalPrice: 35000,
  },
  {
    id: 47,
    name: "Khoai tây Đà Lạt 1kg",
    image: "/images/p47.jpg",
    onHand: 48,
    description: "Khoai tây tươi Đà Lạt.",
    salePrice: 30000,
    originalPrice: 35000,
  },
  {
    id: 48,
    name: "Bắp cải xanh 1kg",
    image: "/images/p48.jpg",
    onHand: 43,
    description: "Bắp cải tươi Đà Lạt.",
    salePrice: 18000,
    originalPrice: 25000,
  },
  {
    id: 49,
    name: "Hành tây 1kg",
    image: "/images/p49.jpg",
    onHand: 60,
    description: "Hành tây nhập khẩu.",
    salePrice: 24000,
    originalPrice: 30000,
  },
  {
    id: 50,
    name: "Ớt chuông 1kg",
    image: "/images/p50.jpg",
    onHand: 52,
    description: "Ớt chuông đỏ xanh vàng.",
    salePrice: 45000,
    originalPrice: 55000,
  }
];
